//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id { get; set; }
        public string FIO { get; set; }
        public System.DateTime DateBirth { get; set; }
        public byte Course { get; set; }
        public string Gender { get; set; }
        public string CodeSpecialty { get; set; }
        public string Specialty { get; set; }
        public string Image { get; set; }
        public string CurrentPhoto
        {
            get
            {
                if (String.IsNullOrEmpty(Image) || String.IsNullOrWhiteSpace(Image))
                {
                    return "/Resources/user_no_photo.jpg";
                }
                else
                {
                    return "/Images/" + Image;
                }
            }
        }
    }
}
